# Simple workflow for deploying static content to GitHub Pages
name: Deploy DEV

on:
  workflow_run:
    workflows: [Build]
    branches: [ 'dev' ]
    types:
      - completed

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo deploying
