# Simple workflow for deploying static content to GitHub Pages
name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo deploying
