name: Deploy DEV

on:
  workflow_run:
    workflows: [Build A]
    branches: [ "main", "dev" ]
    types:
      - completed

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo deploying
